# Generated by Django 6.0.2 on 2026-03-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_populate_projects_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(help_text='e.g. NPTEL, Coursera, Udemy', max_length=100)),
                ('topics', models.CharField(blank=True, help_text='Comma-separated skills, e.g. TCP/IP, Routing', max_length=300)),
                ('status', models.CharField(choices=[('Certified', 'Certified'), ('In Progress', 'In Progress')], default='Certified', max_length=20)),
                ('certificate_link', models.URLField(blank=True, help_text='URL to view the certificate')),
                ('icon', models.CharField(default='fa-solid fa-certificate', help_text='FontAwesome icon class, e.g. fa-solid fa-award', max_length=60)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
