# Generated by Django 6.0.2 on 2026-03-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload certificate logo', null=True, upload_to='certificates/'),
        ),
    ]
